LARGEFONT = ("Arial", 35)
LOGINFONT = ("Arial", 35)
SETTINGS_FONT = ("Arial", 18, 'bold')
SETTINGS_BTN_FONT = ("Arial", 15)
SETTINGS_ABOUT_FONT = ("Arial", 12)
lend_font = ("Arial", 20)
size_add_room_popup = 18
size_add_user_popup = 16
srh_grey = "#d9d9d9"
srh_grey_hover = "#c9c9c9"
srh_orange = "#DF4807"
srh_orange_hover = "#e84c09"
srh_blue = "#00699a"
error_red = "darkred"
nav_bar_hover_color = srh_blue
corner = 20
scroll_corner = 10
border = 0
comboborder = 2
size_add_item_popup = 20
debug_ANSI_style = "\033[33m"
ANSI_style_END = "\033[0m"